### ISSUE TITLE
Selector width is broken

### ISSUE THREAD

**Issue by pyoner** [basf/metis-gui#114]
https://github.com/basf/metis-gui/blob/00a8d517d18eafabd8f58d89f1ff43038d0581cd/src/pages/Search.svelte#L20-L27
![photo_2022-12-09_12-43-02](https://user-images.githubusercontent.com/398748/206651936-28c967ab-24ae-45bb-af0e-24597462100b.jpg)

**Comment by pyoner** [comment]
@blokhin

Can't reproduce the bug, see
You are using the old version because the current version has a `Projects` tab
![image](https://user-images.githubusercontent.com/398748/206654713-b4c03c07-95ec-4ffa-a346-3fcec7f2f7c9.png)

**Comment by pyoner** [comment]
If I remove the `Projects` tab, the selector width looks normal
![image](https://user-images.githubusercontent.com/398748/206671817-328d77b5-6d2a-4309-9774-90f93c0028c6.png)

**Comment by blokhin** [comment]
closing as not reproduced
