### ISSUE TITLE
Filtering collections and fallback to no results with Nodes layout

### ISSUE THREAD

**Issue by blokhin** [basf/metis-gui#182]
The `src/pages/Materials` and `src/pages/Tasks` use `svelte:fragment` filtering, but do not account for the case with no matches (just an empty layout will be shown).

**Comment by blokhin** [comment]
@pyoner could we discuss that briefly?

**Comment by pyoner** [comment]
> @pyoner could we discuss that briefly?

@blokhin I'm busy now, sorry
