### ISSUE TITLE
Router is broken on going back from user profile (/profile)

### ISSUE THREAD

**Issue by blokhin** [basf/metis-gui#92]
A known problem, caused by the [pathfinder](https://github.com/sveltetools/svelte-pathfinder) router: double clicking on an arrow :arrow_left: is required.

**Comment by blokhin** [comment]
Re-opening since the temporary fix

**Comment by PaulMaly** [comment]
I'm not sure I envolved enough to understand specific issue. Usually, going back doesn't require double clicking.

**Comment by PaulMaly** [comment]
Btw, new major, very improved, version of [svelte-pathfinder](https://github.com/sveltetools/svelte-pathfinder) recently released. Make sure you read [change log and migration guide](https://github.com/sveltetools/svelte-pathfinder/blob/master/CHANGELOG.md#400) before update.
