### ISSUE TITLE
Fix an erroneous message "New version of this software available" which appears every minute (but no new version)

### ISSUE THREAD

**Issue by pyoner** [basf/metis-gui#95]
Fix an erroneous message "New version of this software available" which appears every minute (but no new version), see https://github.com/basf/metis-gui/blob/409f06256f32be8904a8215c9c1e44c4518d170e/src/views/Msgbar.svelte#L5

**Comment by pyoner** [comment]
@blokhin 
Can't reproduce this error on `dev` server.
Where does the error appear on `dev` or `prod` server?

I found another error bad manifest path.
I have fixed [manifest path](https://github.com/pyoner/metis-gui/commit/db2dea527cabd75406a999baf67f55c163e3aa5b)

Still can't reproduce the error.

**Comment by blokhin** [comment]
Actually it really disturbed me on the production, so I have to check if it really appears in development as well.

PS manifest was already [fixed](https://github.com/basf/metis-gui/commit/e717917ab386fbe09a657bd8e6f4f7d34ebcb7cf), but still thanks!
