### ISSUE TITLE
Fix font color detection based on the background in the autocomplete component

### ISSUE THREAD

**Issue by pyoner** [basf/metis-gui#96]
Fix font color detection based on the background in the autocomplete component, see https://github.com/basf/metis-gui/blob/master/src/helpers/style.ts (does not work as expected)

**Comment by blokhin** [comment]
![tags-bugs](https://user-images.githubusercontent.com/177388/204295186-bd0bb4cd-92d7-4efc-8e3d-07fbd399fdd5.png)

**Comment by pyoner** [comment]
@blokhin 
How can I get this data?

**Comment by pyoner** [comment]
@blokhin 

I found which component responsible for this:
1. this form is shown in https://github.com/basf/metis-gui/blob/4d6222952bd31917709f3b089ea18a3bcb0527ff/src/views/modals/DataModal.svelte#L60
2. each item in the form is shown as `TagsEdit.svelte` comonent https://github.com/basf/metis-gui/blob/4d6222952bd31917709f3b089ea18a3bcb0527ff/src/views/modals/DataModal.svelte#L58-L63
3. but the font color is missing, see https://github.com/basf/metis-gui/blob/4d6222952bd31917709f3b089ea18a3bcb0527ff/src/views/modals/TagsEdit.svelte#L32

We should fix the style property
